exclude: ^analyses/Synthesis_Old/

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: style-files
        name: style-files (styler)
        entry: Rscript .pre-commit-hooks/style_files.R
        language: system
        files: '\.([rR]|[rR]md|[qQ]md)$'
      - id: lintr
        name: lintr
        entry: Rscript .pre-commit-hooks/lint_check.R
        language: system
        files: '\.([rR]|[rR]md|[qQ]md)$'
