### Packages

```{r}
library(readr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(purrr)
library(here)
library(RColorBrewer)
library(EBImage)
```


```{r}
path1 <- here("analyses", "02_score_distributions", "output_combined.csv")
path2 <- here("analyses", "02_score_distributions", "median_combined.csv")
path3 <- here("analyses", "02_score_distributions", "scorer_key.csv")

output_data <- read_csv(path1, show_col_types = FALSE)
median_data <- read_csv(path2, show_col_types = FALSE)
scorer_key <- read_csv(path3, show_col_types = FALSE, col_types = cols(ID = col_character(), Scorer_Name = col_character()))

score_data <- output_data %>%
  select(Basename, Row, Col, Pos, Scorer1, Score1, Scorer2, Score2, Scorer3, Score3) %>%
  bind_cols(
      median_data %>%
        select(Median_Score)
  )

id_lookup <- setNames(scorer_key$ID, scorer_key$Scorer_Name)

score_data <- score_data %>%
  mutate(across(c(Scorer1, Scorer2, Scorer3), ~ id_lookup[.]))

head(score_data)
```

```{r}
scorer_data <- score_data %>%
  select(starts_with("Scorer")) %>%
  pivot_longer(cols = everything(), names_to = NULL, values_to = "Scorer") %>%
  filter(!is.na(Scorer))

score_values <- score_data %>%
  select(starts_with("Score"), -starts_with("Scorer")) %>%
  pivot_longer(cols = everything(), names_to = NULL, values_to = "Score") %>%
  filter(!is.na(Score))

additional_data <- score_data %>%
  select(Basename, Row, Col, Pos, Median_Score) %>%
  slice(rep(row_number(), each = 3))

score_data_long <- bind_cols(scorer_data, score_values, additional_data)

score_data_long$Scorer <- factor(score_data_long$Scorer, levels = sort(as.numeric(unique(score_data_long$Scorer))))

head(score_data_long)
score_data_long <- score_data_long %>% filter(Score != "[]")

```

```{r}
# Function to normalise class sizes in long data
normalize_rows <- function(data) {
  data <- data %>% select(Score, Median_Score)
  min_count <- data %>% count(Score) %>% summarize(min(n)) %>% pull()
  normalized_data <- data %>%
    group_by(Score) %>%
    sample_n(min_count) %>%
    ungroup()
  return(normalized_data)
}

normalized_data1 <- normalize_rows(score_data_long)
normalized_data1_count <- normalized_data1 %>% count(Score)
print(normalized_data1_count)
```

```{r}
# Function to randomly select 500 rows of a dataframe and calculate how often Score matches Median_Score
calculate_agreement <- function(data) {
  sampled_data <- data %>% sample_n(500)
  sampled_data <- sampled_data %>% mutate(Score = as.numeric(Score), Median_Score = as.numeric(Median_Score))
  agreement <- mean(sampled_data$Score == sampled_data$Median_Score) * 100
  return(agreement)
}

percentage_agreement <- calculate_agreement(normalized_data1)
print(percentage_agreement)
```

```{r}
calculate_difference <- function(data) {
  sampled_data <- data %>% sample_n(500)
  sampled_data <- sampled_data %>% mutate(Score = as.numeric(Score), Median_Score = as.numeric(Median_Score))
  average_difference <- mean(abs(sampled_data$Score - sampled_data$Median_Score))
  return(average_difference)
}
```

```{r}
# Loop this 10,000 times, adding to a vector
generate_agreement_distribution <- function(data, iterations = 10000) {
  agreement_vector <- numeric(iterations)
  for (i in 1:iterations) {
    normalized_data <- normalize_rows(data)
    #agreement <- calculate_agreement(normalized_data)
    agreement <- calculate_difference(normalized_data)
    agreement_vector[i] <- agreement
  }
  return(agreement_vector)
}

difference_distribution <- generate_agreement_distribution(score_data_long, iterations = 10000)
#print(head(agreement_distribution))
```

```{r}
print(head(difference_distribution))
difference_df <- data.frame(mean_abs_diff = difference_distribution)

path <- here("analyses", "02_score_distributions", "percentagreedist.png")
png(path, height=1000, width=1000)
# Plot this distribution
ggplot(difference_df, aes(x = mean_abs_diff)) +
  geom_histogram(binwidth = 0.01, fill = "blue", color = "black") +
  geom_vline(xintercept = 0.38, color = "red", linetype = "dashed", size = 1) +
  scale_x_continuous(breaks = seq(0, 100, by = 5)) +
  labs(x = "Mean Absolute Difference",
       y = "Frequency") +
  theme_minimal() + 
  theme(
    text = element_text(size = 16),
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 14),
  )
dev.off()
```

```{r}
mean_diff <- mean(difference_distribution)
print(mean_diff)
sd_diff <- sd(difference_distribution)

probability <- 1-pnorm(0.38, mean = mean_diff, sd = sd_diff)
print(probability * 100)
```

```{r}
# Plot this distribution with a red line at 65.4%
path <- here("analyses", "02_score_distributions", "meanerrordist.png")
png(path, height=1000, width=1000)
ggplot(agreement_df, aes(x = agreement)) +
  geom_histogram(binwidth = 0.4, fill = "blue", color = "black") +
  geom_vline(xintercept = 65.4, color = "red", linetype = "dashed", size = 1) +
  scale_x_continuous(breaks = seq(0, 100, by = 5)) +
  labs(x = "Agreement Percentage",
       y = "Frequency") +
  theme_minimal() + 
  theme(
    text = element_text(size = 16),
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 14),
  )
dev.off()
```

```{r}
# Find P(score <= 65.4 in distribution)
mean_agreement <- mean(agreement_distribution)
print(mean_agreement)
sd_agreement <- sd(agreement_distribution)

probability <- pnorm(65.4, mean = mean_agreement, sd = sd_agreement)
print(probability * 100)

# This is the percentage of time that model outperforms the humans.

```